### ISSUE TITLE
Write tech.xing.com article

### ISSUE THREAD

**Issue by danielknott** [xing/calabash-launcher#104]
Let's write an article before we open source it. We can publish it together. Everyone who has a blog can then re-blog the tech.xing.com post to get more visibility.

I started a blog post here:

https://medium.com/p/97972d9ab161/edit

@iltempo can we change the author to XING instead of the one who created the draft?

**Comment by danielknott** [comment]
please take a final look at the article. @BasThomas @iltempo @JoeSSS @dhartwich1991 @q231950

**Comment by JoeSSS** [comment]
We should decide if we want to resurrect physical device functionality before we post the article, or just mention that it will be available there.

**Comment by JoeSSS** [comment]
@danielknott I added some comments to the article right on Medium (as I don't have rights to change the original text). 
+ the PR about physical devices is in review #109

**Comment by JoeSSS** [comment]
@danielknott the article is great from my point of view 👍 
I believe that we can publish it at Monday. #109 should be merged soon.

**Comment by JoeSSS** [comment]
Why not writing two articles? :) For a long time I wanted to write something motivational for Calabash community. http://www.waysoftesting.com/?p=262&preview=true @danielknott do you think it is fine to publish it in the same day and reference to the tech.xing.com from there?

**Comment by BasThomas** [comment]
The link you provided gives a 404, but I don't see a reason why not. Would it make more sense to not post the two posts at the same time though? Not sure if that would be the best way to go. But definitely 2 > 1!
