### ISSUE TITLE
Cover removed functionality properly

### ISSUE THREAD

**Issue by BasThomas** [xing/calabash-launcher#11]
We need to return back the functionality that got disabled because they were connected to the very specific implementation of our framework.

1. Languages #17 (covered)
2. Physical device (installation of the frameworks + find the device IP) #109 (covered)
3. Build Picker #70 (covered)
4. Localization

**Comment by BasThomas** [comment]
We can split up this ticket into multiple tickets if we feel like that would make sense.

**Comment by JoeSSS** [comment]
Split the first part of this ticket: https://github.com/JoeSSS/calabash-launcher/issues/17

**Comment by JoeSSS** [comment]
New settings section was added for physical device support:
<img width="580" alt="screen shot 2017-11-11 at 22 05 20" src="https://user-images.githubusercontent.com/18147900/32693519-add622fe-c72c-11e7-9950-7197900eba53.png">

**Comment by JoeSSS** [comment]
Close this one, as the remaining point will take time, so I create a new ticket for it
