### ISSUE TITLE
Investigate crashes in the latest release

### ISSUE THREAD

**Issue by JoeSSS** [xing/calabash-launcher#137]
We have 3 crashes in the last release:

https://rink.hockeyapp.net/manage/apps/687667/app_versions/1/crash_reasons/203943413
https://rink.hockeyapp.net/manage/apps/687667/app_versions/1/crash_reasons/203947055 (possible fixed in #139)
https://rink.hockeyapp.net/manage/apps/687667/app_versions/1/crash_reasons/203942335 (possible fixed in #139)

It could happen because we somehow lose the path to the test folder (should also investigate this)

**Comment by q231950** [comment]
@JoeSSS  I don’t seem to have access to the app, could you please have a look at permissions 🗝

**Comment by BasThomas** [comment]
Same for me.

**Comment by JoeSSS** [comment]
Done @BasThomas  @q231950

**Comment by BasThomas** [comment]
Still get an "app not found" error.

**Comment by JoeSSS** [comment]
Did you confirm the invitation on you XING hockey account?

**Comment by BasThomas** [comment]
Ah, probably got an email. Haven't set that up here. Will check tomorrow morning 👍

**Comment by JoeSSS** [comment]
The issue seems to be fixed by fixing other crashes. In the last version we have 0 crashes.
