### ISSUE TITLE
App crashes on start when starting it by double-clicking and not from Xcode

### ISSUE THREAD

**Issue by JoeSSS** [xing/calabash-launcher#144]
This is reproducible in 100% of cases. The library works perfect when running from Xcode but not by clicking on the app in products.

```
Dyld Error Message:
  Library not loaded: @rpath/CommandsCore.framework/Versions/A/CommandsCore
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/Calabash_Launcher-blwtwqkffqatxtayzxfvvabuleba/Build/Products/Debug/Calabash Launcher.app/Contents/MacOS/Calabash Launcher
  Reason: image not found
```
@q231950 please take a look, maybe we should copy the resources to the main bundle?

**Comment by q231950** [comment]
@JoeSSS I think one of the frameworks is only linked and not embedded. I’ll have a look in ~6 hours

**Comment by JoeSSS** [comment]
@q231950 true. Can you please review #145 :)
