### ISSUE TITLE
Build CommandsCore in the build phase

### ISSUE THREAD

**Issue by JoeSSS** [xing/calabash-launcher#78]
Currently Launcher is connected to the Xcode version, as the binary is built and placed in the project without rebuild

**Comment by JoeSSS** [comment]
@q231950 we need some help here :)

**Comment by q231950** [comment]
I’ll have a look. Do you completely dislike the variant where people have to run ‘swift build’ when they want to build on their? Normal users would always want to download a compiled product, wouldn’t they?

**Comment by JoeSSS** [comment]
I don't completely dislike the `swift build` variant, but hoped that there can be smth nicer :)
