### ISSUE TITLE
Re-arrange buttons by logical clusters

### ISSUE THREAD

**Issue by JoeSSS** [xing/calabash-launcher#94]

**Comment by BasThomas** [comment]
Can you give an explanation of what this would change?

**Comment by JoeSSS** [comment]
@BasThomas this will change the look of the app, and make the elements belong to corresponding cluster of elements. The PR is already there: #120

New look:

<img width="1258" alt="screen shot 2018-01-01 at 12 42 11" src="https://user-images.githubusercontent.com/18147900/34467445-5f96dba4-eef2-11e7-984b-07d369c75ca3.png">
