### ISSUE TITLE
Align the Console Input Area

### ISSUE THREAD

**Issue by danielknott** [xing/calabash-launcher#96]
on the right side of the window there is a gap which looks not nice. Furthermore it would be great to get some more spacing between the log output field and the console input. Maybe we can also change the background color.

**Comment by BasThomas** [comment]
It seems like this is still not properly aligned? (as per https://user-images.githubusercontent.com/18147900/32609542-4f0c18aa-c560-11e7-9663-d44e1c759187.png)

**Comment by JoeSSS** [comment]
@BasThomas What do you mean? Looks good from my point of view
![screen shot 2018-01-01 at 13 04 03](https://user-images.githubusercontent.com/18147900/34467506-8ca05b50-eef4-11e7-9ca0-1373ba7ddd19.png)

**Comment by JoeSSS** [comment]
@BasThomas can we close this one?

**Comment by BasThomas** [comment]
Yep, it’s fixed now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
